In [6]:
# 1. Импортирование библиотеки Numpy под общепринятым сокращением np
import numpy as np

In [7]:
# 2. Примеры создания массивов
arr_1 = np.array([1, 2, 3, 4]) # демонстрация преобразования обычного списка в массив numpy
print("arr_1: ", arr_1, arr_1.dtype, '\n')

arr_2 = np.array([[234, 234.54, "hello"], [34, 532, 123]]) # преобразование двумерного списка
print("arr_2: ", arr_2, arr_2.dtype, '\n')

zero = np.zeros((3, 3)) # создание массива numpy из нулей 3x3. Можно задать одномерный массив без передачи кортежа в функцию, например np.zeros(6)
print("zero: ", zero, '\n')

one = np.ones((2, 2, 3)) # создание массива numpy из единиц
print("one: ", one, '\n')

arng_1 = np.arange(10) # генерация массива из последовательности
print("arng_1: ", arng_1, '\n')

arng_2 = np.arange(0, 3.4, 0.3) # в отличие от обычного range работает с дробными чмслами
print("arng_2: ", arng_2, '\n')

array_full = np.full((3, 3), 10) # функция создания массива с заданным размером и наполняемым числом
print("array_full: ", array_full, '\n')

arr_empt = np.empty((2, 2)) # создание пустого массива (без инициализации значений)
print("arr_empt: ", arr_empt, '\n')

arr_1:  [1 2 3 4] int64 

arr_2:  [['234' '234.54' 'hello']
 ['34' '532' '123']] <U32 

zero:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

one:  [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 

arng_1:  [0 1 2 3 4 5 6 7 8 9] 

arng_2:  [0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3] 

array_full:  [[10 10 10]
 [10 10 10]
 [10 10 10]] 

arr_empt:  [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]] 



In [8]:
# 3. Демонстрация атрибутов
print("Форма массива one: ", one.shape)
print("Тип данных массива one: ", one.dtype)
print("Кол-во измерений массива one: ", one.ndim)
print("Общее кол-во элементов массива one: ", one.size)

Форма массива one:  (2, 2, 3)
Тип данных массива one:  float64
Кол-во измерений массива one:  3
Общее кол-во элементов массива one:  12


In [9]:
# 4. Примеры индексирования и срезов
print(arr_2[1, 1]) # Получение отдельного элемента из массива arr_2 (индексация в квадратных скобках через запятую)
print(arr_2[:2, 1:3]) # Извлечение подмассива с помощью среза

532
[['234.54' 'hello']
 ['532' '123']]


In [10]:
# 5. Примеры векторных оперцаий и базовых статистик
first = np.arange(1, 9)
second = np.arange(3, 11)

sum = first + second # Поэлементарное сложение
print(sum)

diff = second - first # Поэлементарное вычитание
print(diff)

mult = first * second # Поэлементарное умножение
print(mult)

print(np.mean(second)) # среднее массива
print(np.median(second)) # медиана массива
print(np.std(second)) # стандартное отклонение массива

[ 4  6  8 10 12 14 16 18]
[2 2 2 2 2 2 2 2]
[ 3  8 15 24 35 48 63 80]
6.5
6.5
2.29128784747792
