In [ ]:
# Импортирование библиотеки Numpy под устоявшимся псевдонимом np
import numpy as np

In [22]:
arr_1 = np.array([1, 2, 3, 4]) # демонстрация преобразования обычного массива в массив numpy
print("arr_1: ", arr_1, arr_1.dtype, '\n')

arr_2 = np.array([[234, 234.54, "hello"], [34, 532, 123]]) # преобразование двумерного списка
print("arr_2: ", arr_2, arr_2.dtype, '\n')

zero = np.zeros((3, 3)) # создание массива numpy из нулей 3x3. Можно задать одномерный массив без передачи кортежа в функцию, например np.zeros(6)
print("zero: ", zero, '\n')

one = np.ones((2, 2, 3)) # создание массива numpy из единиц
print("one: ", one, '\n')

arng_1 = np.arange(10) # генерация массива из последовательности
print("arng_1: ", arng_1, '\n')

arng_2 = np.arange(0, 3.4, 0.3) # в отличие от обычного range работает с дробными чмслами
print("arng_2: ", arng_2, '\n')


arr_1:  [1 2 3 4] int64 

arr_2:  [['234' '234.54' 'hello']
 ['34' '532' '123']] <U32 

zero:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

one:  [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 

arng_1:  [0 1 2 3 4 5 6 7 8 9] 

arng_2:  [0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3] 

